# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://courses.shaffermusic.com
title: Kris Shaffer's course materials - CU–Boulder School of Music
subtitle: 
author: Kris Shaffer
simple_search: http://google.com/search
description: 

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: kris.shaffer@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
baseurl: http://courses.shaffermusic.com

markdown: kramdown